let a = "Ｎａｍｅ:-          Ｓｃｈｏｏｌ:-";
console.log(a);
let name = "Joseph David        Tagore Memorial School";
console.log(name);
let i="";
console.log(i);
let c = "𝙂𝙧𝙖𝙙𝙚               𝓢𝓮𝓬𝓽𝓲𝓸𝓷";
console.log(c);
let grade = "A+                   A";
console.log(grade);
let o="";
console.log(o);
let f = "🅡🅞🅛🅛🅝🅞";
console.log(f);
let rollno = 15512;
console.log(rollno);
let v="";
console.log(v);
let e = "Ｍａｒｋｓ:-";
console.log(e);
let u="";
console.log(u);
let marks1 = "English    96";
console.log(marks1);
let marks2 = "Hindi      114";
console.log(marks2);
let marks3 = "Science    68";
console.log(marks3);